#pragma config(Motor,  port1,           ld1,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           ld2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rd1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rd2,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "parallelDrive.c"

parallel_drive drive;

task main() {
	initializeDrive(drive);
	setLeftMotors(drive, 2, ld1, ld2);
	setRightMotors(drive, 2, rd1, rd2);

	while (true) driveRuntime(drive);
}
