#pragma config(Motor,  port2,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rbd,           tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "parallelDrive.c"

parallel_drive drive;

task main() {
	initializeDrive(drive);
	setLeftMotors(drive, 2, lfd, lbd);
	setRightMotors(drive, 2, rfd, rbd);

	while (true) driveRuntime(drive);
}
