#pragma config(Sensor, in1,    Yaw,            sensorGyro)
#pragma config(Sensor, dgtl3,  leftE,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightE,         sensorQuadEncoder)
#pragma config(Motor,  port2,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rbd,           tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "parallelDrive.c"

parallel_drive drive;
float da, dl, dr, ra, rl, rr;

task main() {
	initializeDrive(drive);
	setLeftMotors(drive, 2, lfd, lbd);
	setRightMotors(drive, 2, rfd, rbd);
	attachGyro(drive, Yaw);
	attachEncoderL(drive, leftE);
	attachEncoderR(drive, rightE);

	while (true) {
		driveRuntime(drive);

		da = encoderVal(drive);
		dl = encoderVal_L(drive);
		dr = encoderVal_R(drive);
		ra = encoderVal(drive, true);
		rl = encoderVal_L(drive, true);
		rr = encoderVal_R(drive, true);

		if (vexRT[Btn5D] == 1) drive.width = calculateWidth(drive);

		if (vexRT[Btn6D] == 1) resetEncoders(drive);
	}
}
